spring:
  h2:
    console:
      enable: true
      path: /h2-console
  session:
    timeout: 86400
    jdbc:
      initialize-schema: always

  datasource:
    url: jdbc:h2:tcp://localhost/~/test;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 20
        one-indexed-parameters: true
hodolman:
  jwt-key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
server:
  servlet:
    session:
      cookie:
        max-age: 172800


